version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    networks:
      - app-network
  fastapi:
    build: ./server
    container_name: clinic_server
    depends_on:
      - db
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      .env.example

volumes:
  pgdata:

networks:
  app-network: