version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"


volumes:
  pgdata:
