version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB:        ${POSTGRES_DB}
      POSTGRES_USER:      ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
    networks:
      - app-network
  fastapi:
    build: ./server
    container_name: clinic_server
    depends_on:
      - db
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      DB_HOST:      ${DB_HOST}
      DB_PORT:      ${DB_PORT}
      DB_NAME:      ${DB_NAME}
      DB_USER:      ${DB_USER}
      DB_PASSWORD:  ${DB_PASSWORD}

volumes:
  pgdata:

networks:
  app-network: