version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB:        ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER:      ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
    networks:
      - app-network
  fastapi:
    build: ./server
    container_name: clinic_server
    depends_on:
      - db
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      DB_HOST:      ${{ secrets.DB_HOST }}
      DB_PORT:      ${{ secrets.DB_PORT }}
      DB_NAME:      ${{ secrets.DB_NAME }}
      DB_USER:      ${{ secrets.DB_USER }}
      DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}

volumes:
  pgdata:

networks:
  app-network: