name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: compose install
        run: sudo apt-get install docker-compose -y

      - name: up db
        run: docker-compose up -d db

      - name: waiting for compose to start
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec clinic_db pg_isready -U $POSTGRES_USER; do
            sleep 2
          done

      - name: dependencies
        run: |
          pip install -r requirements.txt

      - name: linters
        run: make lint

      - name: env var export
        run: |
          set -a
          source server/.env.example
          set +a

      - name: Run tests
        run: make test
