name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Create .env from secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.example
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.example
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env.example
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env.example
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.example

      - name: Start services (db + fastapi)
        run: docker-compose up -d --build

      - name: Wait for FastAPI to be ready
        run: |
          echo "Waiting for FastAPI to be ready..."
          until curl -s http://localhost:8000/docs; do
            echo "Waiting..."
            sleep 2
          done
          echo "FastAPI is up!"

      - name: Run tests inside FastAPI container
        run: docker exec clinic_server make test

      - name: Run linters inside FastAPI container
        run: docker exec clinic_server make lint
